- name: Clone repository
  git:
    repo: "{{ item.repo }}"
    dest: "{{ [eng_repo_base_dir, item.dest | default (item.repo | regex_replace('^(?:.+/)?([^/]+)$', '\\1'))] | join('/') | realpath }}"
    remote: "{{ item.remote | default(eng_repos_default_remote_name) }}"
  loop: "{{ batch }}"
  async: 60
  poll: 0
  register: git_clone_async_results

- name: Wait for git clone to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ git_clone_async_results.results }}"
  register: git_clone_async_status_results
  until: git_clone_async_status_results.finished
  retries: 60
  delay: 10
  when: git_clone_async_status_results is defined
